import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar'
const inter = Inter({ subsets: ['latin'] })
import sidebarStyles from './styles/sidebar.module.css'

export const metadata = {
  title: 'Badrudin - Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* Left Sidebar */}
        <div className={`container p-20 justify-center items-center w-2/4 h-screen `}>
          <Sidebar />
        </div>

        {/* Right Content */}
        <div className={`h-screen overflow-y-auto`}>
          {children}
        </div>

      </body>
    </html>
  )
}
